### PR TITLE
fix: update package URLs

### PR DESCRIPTION
**Pull request by dhdaines**

### CODE REVIEW

**Comment by dhdaines** [comment]
Still failing! WTF!!!

**Comment by roedoejet** [comment]
please wait to merge to master until tests pass!

**Comment by dhdaines** [comment]
Not our fault that they don't pass, as Eric's other PRs attest

**Comment by joanise** [comment]
Well, that's never really true. It's our fault out tests were not tolerant to unpkg instability. But it'll be fixed shortly, with my PR Aidan just approved.

**Pull request merged**
