### PR TITLE
feat: including generator meta tag in .readalong files

### PR DESCRIPTION
**Pull request by roedoejet**
Rebased duplicate of https://github.com/ReadAlongs/Studio/pull/225 - please either close this one or close #225 and re-request the reviews here.

### CODE REVIEW

**Review by deltork — APPROVED** [review]
ready for merge

**Comment by joanise** [comment]
Just discovered an issue while discussing #229, repeating the comment here since it's relevant here:

> Oh, wait, no, but that uncovers a bug in versioning-patch: `VERSION` and `__version__` were previously meant the be tied, with `VERSION` being Major.minor and `__version__` being generated as Major.minor.patch. On the other hand, the `format_version` introduced here will need a new variable, not defined before, because we cannot assume it's always going to be the same as readalongs' Major.minor version: we might add features or make breaking changes that don't affect for the .readalong format, in which case we'll be the software minor and/or major, but we won't change the format version unless that too gets modified.

**Comment by joanise** [comment]
Also, `cli-guide.md` has a reference to `read-along-1.0.dtd` which needs to get bumped to 1.1.

**Review by joanise — CHANGES_REQUESTED** [review]
Please create a new constant, as mentioned above, for `format_version`.

**Comment by joanise** [comment]
Since I broke this code with my other PR, I rebased it for you and created the new variable. @deltork take a look and make sure it's OK. I'll approve, but it's also worth a re-review by someone else. @roedoejet ?

**Comment by deltork** [comment]
> Please create a new constant, as mentioned above, for `format_version`.

Thanks for doing this

> Since I broke this code with my other PR, I rebased it for you and created the new variable. @deltork take a look and make sure it's OK. I'll approve, but it's also worth a re-review by someone else. @roedoejet ?

Looks good!

**Review by joanise — APPROVED** [review]
My requested changes are done.

**Pull request merged**
